class_name States

const IDLE         := "IDLE"
const TYPING       := "TYPING"
const THINKING     := "THINKING"
const SUCCESS      := "SUCCESS"
const ERROR        := "ERROR"
const AWAY         := "AWAY"
const DEBUGGING    := "DEBUGGING"
const RUNNING      := "RUNNING"
const TERMINAL     := "TERMINAL"
const FILE_SWITCH  := "FILE_SWITCH"
const FILE_CREATE  := "FILE_CREATE"
const FILE_DELETE  := "FILE_DELETE"
const FILE_RENAME  := "FILE_RENAME"
